# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [4]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [5]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [6]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [7]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [8]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [9]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [11]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [12]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [13]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [14]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.55167621 0.80568568 0.44583378 0.25862208 0.07043699]
 [0.30510318 0.51795384 0.64484625 0.05451928 0.03972515]
 [0.83523613 0.66274376 0.6947893  0.04882412 0.83245422]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]

[[-0.2930719   0.59219525  0.59875564  0.74831453 -0.39912787]
 [-0.45329425  0.97660731 -0.20669348  2.86680947 -0.43870459]
 [ 0.84832137 -0.92449506 -1.19393856  1.27038009  0.25000074]
 [ 0.70864624 -0.69899007  1.24171482  0.93634856  0.50225373]
 [ 0.7669805  -0.12255538 -1.11346671 -0.08991341  1.18674242]
 [-2.96814781  1.47489379 -0.28141331 -1.14950297  0.42798659]
 [ 0.79877807 -0.56597891 -0.65282728  1.66503049 -1.09366907]
 [ 0.51101829 -1.90159051  1.22628728  0.34085734  0.56039039]
 [-0.84642495 -0.68319958 -0.40279339 -0.62153108 -0.599165  ]
 [-0.34394483 -1.8043444   1.45166361  0.70219037  2.5885354 ]]


In [15]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5402347176110406
1.1012884048165579


In [16]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.03972515193696324
2.866809469690187


In [17]:
# break here for next video!

In [18]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.54360968  0.98198753  0.27834735  0.46599281  0.98114317  0.41336872
 -0.47876992  1.6495076  -0.87562995 -2.36078701 -0.76167178 -0.32136802
 -0.9986253   0.23896709 -1.01526411 -0.78536501 -0.0368493  -0.25564473
  0.89261238]
-0.478769916972336


In [19]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.98114317  0.41336872 -0.47876992  1.6495076  -0.87562995]


In [20]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.54360968  0.46599281 -0.47876992 -2.36078701 -0.9986253 ]


In [21]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.55167621 0.80568568 0.44583378 0.25862208 0.07043699]
 [0.30510318 0.51795384 0.64484625 0.05451928 0.03972515]
 [0.83523613 0.66274376 0.6947893  0.04882412 0.83245422]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]
0.6448462520705511
0.6448462520705511


In [22]:
print(rand_mat[0:2,1:3])

[[0.80568568 0.44583378]
 [0.51795384 0.64484625]]


In [23]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.54360968  0.98198753  0.27834735  0.46599281  0.98114317  0.41336872
 -0.47876992  1.6495076  -0.87562995 -2.36078701 -0.76167178 -0.32136802
 -0.9986253   0.23896709 -1.01526411 -0.78536501 -0.0368493  -0.25564473
  0.89261238]

[ 0.54360968  0.98198753  0.27834735  4.          4.          0.41336872
 -0.47876992  1.6495076  -0.87562995 -2.36078701 -0.76167178 -0.32136802
 -0.9986253   0.23896709 -1.01526411 -0.78536501 -0.0368493  -0.25564473
  0.89261238]

[ 0.54360968  0.98198753  0.27834735  1.          2.          0.41336872
 -0.47876992  1.6495076  -0.87562995 -2.36078701 -0.76167178 -0.32136802
 -0.9986253   0.23896709 -1.01526411 -0.78536501 -0.0368493  -0.25564473
  0.89261238]


In [24]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.55167621 0.80568568 0.44583378 0.25862208 0.07043699]
 [0.30510318 0.51795384 0.64484625 0.05451928 0.03972515]
 [0.83523613 0.66274376 0.6947893  0.04882412 0.83245422]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]

[[0.55167621 0.80568568 0.44583378 0.25862208 0.07043699]
 [0.30510318 0.51795384 0.64484625 0.         0.        ]
 [0.83523613 0.66274376 0.6947893  0.         0.        ]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]


In [25]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.55167621 0.80568568 0.44583378]
 [0.30510318 0.51795384 0.64484625]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [26]:
print(rand_mat)

[[3.         3.         3.         0.25862208 0.07043699]
 [3.         3.         3.         0.         0.        ]
 [0.83523613 0.66274376 0.6947893  0.         0.        ]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]


In [27]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.25862208 0.07043699]
 [3.         3.         3.         0.         0.        ]
 [0.83523613 0.66274376 0.6947893  0.         0.        ]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]


In [28]:
# break here for next video

In [29]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.58236413  1.012423   -0.85461098  0.4794643  -0.19314215 -0.14117978
 -0.7552069   0.06590289  0.40000894 -0.36939261 -0.76376184 -0.16271494
 -1.33977357  0.88683654  1.04303272]
[False  True False  True False False False  True  True False False False
 False  True  True]
[1.012423   0.4794643  0.06590289 0.40000894 0.88683654 1.04303272]


In [30]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.2930719   0.59219525  0.59875564  0.74831453 -0.39912787]
 [-0.45329425  0.97660731 -0.20669348  2.86680947 -0.43870459]
 [ 0.84832137 -0.92449506 -1.19393856  1.27038009  0.25000074]
 [ 0.70864624 -0.69899007  1.24171482  0.93634856  0.50225373]
 [ 0.7669805  -0.12255538 -1.11346671 -0.08991341  1.18674242]
 [-2.96814781  1.47489379 -0.28141331 -1.14950297  0.42798659]
 [ 0.79877807 -0.56597891 -0.65282728  1.66503049 -1.09366907]
 [ 0.51101829 -1.90159051  1.22628728  0.34085734  0.56039039]
 [-0.84642495 -0.68319958 -0.40279339 -0.62153108 -0.599165  ]
 [-0.34394483 -1.8043444   1.45166361  0.70219037  2.5885354 ]]
[0.59219525 0.59875564 0.74831453 0.97660731 2.86680947 0.84832137
 1.27038009 0.25000074 0.70864624 1.24171482 0.93634856 0.50225373
 0.7669805  1.18674242 1.47489379 0.42798659 0.79877807 1.66503049
 0.51101829 1.22628728 0.34085734 0.56039039 1.45166361 0.70219037
 2.5885354 ]


In [31]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.58236413  1.012423   -0.85461098  0.4794643  -0.19314215 -0.14117978
 -0.7552069   0.06590289  0.40000894 -0.36939261 -0.76376184 -0.16271494
 -1.33977357  0.88683654  1.04303272]

[-0.58236413 -5.         -0.85461098  0.4794643  -0.19314215 -0.14117978
 -0.7552069   0.06590289  0.40000894 -0.36939261 -0.76376184 -0.16271494
 -1.33977357 -5.         -5.        ]


In [32]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [33]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [34]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.2930719   0.59219525  0.59875564  0.74831453 -0.39912787]
 [-0.45329425  0.97660731 -0.20669348  2.86680947 -0.43870459]
 [ 0.84832137 -0.92449506 -1.19393856  1.27038009  0.25000074]
 [ 0.70864624 -0.69899007  1.24171482  0.93634856  0.50225373]
 [ 0.7669805  -0.12255538 -1.11346671 -0.08991341  1.18674242]
 [-2.96814781  1.47489379 -0.28141331 -1.14950297  0.42798659]
 [ 0.79877807 -0.56597891 -0.65282728  1.66503049 -1.09366907]
 [ 0.51101829 -1.90159051  1.22628728  0.34085734  0.56039039]
 [-0.84642495 -0.68319958 -0.40279339 -0.62153108 -0.599165  ]
 [-0.34394483 -1.8043444   1.45166361  0.70219037  2.5885354 ]]



In [35]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.25862208 0.07043699]
 [3.         3.         3.         0.         0.        ]
 [0.83523613 0.66274376 0.6947893  0.         0.        ]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]

[[-0.2930719   0.59219525  0.59875564  0.74831453 -0.39912787]
 [-0.45329425  0.97660731 -0.20669348  2.86680947 -0.43870459]
 [ 0.84832137 -0.92449506 -1.19393856  1.27038009  0.25000074]
 [ 0.70864624 -0.69899007  1.24171482  0.93634856  0.50225373]
 [ 0.7669805  -0.12255538 -1.11346671 -0.08991341  1.18674242]
 [-2.96814781  1.47489379 -0.28141331 -1.14950297  0.42798659]
 [ 0.79877807 -0.56597891 -0.65282728  1.66503049 -1.09366907]
 [ 0.51101829 -1.90159051  1.22628728  0.34085734  0.56039039]
 [-0.84642495 -0.68319958 -0.40279339 -0.62153108 -0.599165  ]
 [-0.34394483 -1.8043444   1.45166361  0.70219037  2.5885354 ]]
[[3.         3.         3.         0.25862208 0.07043699]
 [3.         3.    

In [36]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.25862208 0.07043699]
 [3.         3.         3.         0.         0.        ]
 [0.83523613 0.66274376 0.6947893  0.         0.        ]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]

[[3.         3.         3.         0.25862208 0.07043699]
 [3.         3.         3.         0.         0.        ]
 [0.83523613 0.66274376 0.6947893  0.         0.        ]
 [0.78569267 0.96044314 0.37311597 0.58325275 0.88039612]
 [0.66976888 0.58251505 0.66041276 0.80784221 0.43397842]]
