In [8]:
import numpy as np
l1 = 100
l2 = 200

val = np.add(l1,l2)
print(val)



300
1.24.0


In [11]:
print(np.__version__)

1.24.0


In [19]:
a=np.array([10,20,30])
print(a)

[10 20 30]


In [20]:
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [24]:
a[0][1]

20

In [29]:
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [30]:
a[1][0][1]

60

In [31]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a+b
print(c)
c = c*a
print(c)
print(c[2])

[1 5 7 7 9]
[ 1 10 21 35 72]
21
