single dimentional array

In [2]:
import numpy as np

a=np.zeros(3)

print(a)

[0. 0. 0.]


2 dimentional

In [1]:
import numpy as np

a=np.zeros([2,3])

print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


3 dimentional

In [14]:
import numpy as np

a=np.zeros([2,3,3])

print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
np.full([2,3,3],10) #full will allow to fill any number in arrays like 10

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [48]:
np.random.rand(2,3,4) #random values 0 umdi 1 lopala fill avthai

array([[[0.65189304, 0.02078938, 0.8258223 , 0.09961767],
        [0.15994014, 0.43416614, 0.33302356, 0.58127265],
        [0.10874642, 0.06664758, 0.77517891, 0.71755515]],

       [[0.91632367, 0.22954368, 0.57159413, 0.07287783],
        [0.64044762, 0.97183438, 0.46540381, 0.83721153],
        [0.69714031, 0.14482846, 0.00922581, 0.04255615]]])

In [49]:
np.ones([2,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [50]:
np.eye(2) #diognal eliments 1 untai

array([[1., 0.],
       [0., 1.]])

In [51]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

NUmerical ranges methods 

In [52]:
a =np.arange(10,20,1)
print(a)

[10 11 12 13 14 15 16 17 18 19]


[1 5 7 7 9]
[ 1 10 21 35 72]
21
